FROM node:20-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./
RUN corepack enable && pnpm install --frozen-lockfile --prod || pnpm install --prod
RUN apk add --no-cache ffmpeg

COPY src ./src
COPY public ./public
COPY openapi ./openapi
COPY sdk ./sdk

EXPOSE 4000
CMD ["node", "src/server.js"]